name: eResidensi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.4.0+1
  flutter_custom_clippers: ^1.1.1
  provider: 3.0.0
  http: ^0.12.1
  flutter_spinkit: ^4.1.2+1
  intl: ^0.16.1
  flutter_alert: ^0.4.0
  flutter_launcher_icons: ^0.7.5
  shared_preferences: ^0.5.7+3
  flutter_open_whatsapp: ^0.1.2
  animated_text_kit: ^2.2.0
  flutter_material_pickers: ^1.5.4
  barcode_scan: 3.0.1
  geolocator: ^5.3.1
  location: ^3.0.0
  rich_alert: ^0.1.32

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_second.png"
  adaptive_icon_background: "#00FFFF"
  adaptive_icon_foreground: "assets/images/logo_second.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceSerifPro
      fonts:
        - asset: assets/fonts/SourceSerifPro-Bold.ttf

    - family: Ubuntu
      fonts:
      - asset: assets/fonts/Ubuntu-Regular.ttf
      - asset: assets/fonts/Ubuntu-Bold.ttf
        weight: 700
      - asset: assets/fonts/Ubuntu-Light.ttf
        weight: 200

    - family: IconAwesome4
      fonts:
      - asset: assets/fonts/IconAwesome4.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages