/// Flutter icons IconAwesome4
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconAwesome4
///      fonts:
///       - asset: fonts/IconAwesome4.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconAwesome4 {
  IconAwesome4._();

  static const _kFontFam = 'IconAwesome4';
  static const _kFontPkg = null;

  static const IconData home_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_alt = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info_circled = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_big = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData login = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xf015, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_retro = IconData(0xf083, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cogs = IconData(0xf085, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text = IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_text_inv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_out_alt = IconData(0xf2f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign_in_alt = IconData(0xf2f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_circle_left = IconData(0xf359, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_alt_circle_right = IconData(0xf35a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
